###
# Get clients
GET http://127.0.0.1:8000/clients

###
# Create Client
POST http://127.0.0.1:8000/clients

{
    "first_name": "Jean",
    "name": "Dupont"
}

###
# Get client
GET http://127.0.0.1:8000/clients/1

###
# Update Client
PUT http://127.0.0.1:8000/clients/1

{
    "first_name": "Jean",
    "name": "Du Pont"
}

###
# Delete Client
DELETE http://127.0.0.1:8000/clients/1